#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'qrcode==5.3','console_scripts','qr'
__requires__ = 'qrcode==5.3'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('qrcode==5.3', 'console_scripts', 'qr')()
    )
